services:
  frontend:
    image: oven/bun:1
    container_name: hcms-v2-fe-dev
    working_dir: /app
    command: sh -c "bun install && bun run dev --host 0.0.0.0"
    volumes:
      - .:/app
      - /app/node_modules  # Preserve node_modules in container
    ports:
      - "5173:5173"
    networks:
      - hcms-network
    environment:
      - VITE_API_TARGET=http://localhost:8080

networks:
  hcms-network:
    external: true
    name: hcms-global-network
